# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtDes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QInputDialog
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(399, 608)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 260, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 210, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 140, 271, 41))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 370, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.adress = ''

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Выберите файл переписки"))
        self.pushButton_2.setText(_translate("MainWindow", "Как пользоваться программой?"))
        self.label.setText(_translate("MainWindow", "Анализатор чата whatsapp"))
        self.pushButton_3.setText(_translate("MainWindow", "Получить результат"))
        self.pushButton_3.setEnabled(False)
        self.pushButton.clicked.connect(self.pick_file)
        self.pushButton_3.clicked.connect(self.analys)

    def pick_file(self):
        self.open_dialog_box()
        self.pushButton_3.setEnabled(True)

    def open_dialog_box(self):
        filename = QFileDialog.getOpenFileNames(directory=r'\Users\anton\Downloads', filter="txt file (*.txt)")
        self.adress = filename[0][0]

    def open_result(self, dict):
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog, dict)
        Dialog.show()
        Dialog.exec_()

    def analys(self):
        file = open(self.adress, 'r', encoding='utf-8').read()
        file = file.split('\n')
        file1 = []
        for i in range(len(file)):
            if file[i] != '':
                file1.append(file[i])
        file = ' '.join(file1).split(' - ')
        sleep = ['Спокойн', 'сладк', 'снов', 'ночи', 'сны']
        morn = ['Доброе утро', 'утра']
        for i in range(len(file)):
            if '.2017,' in file[i] or '.2020,' in file[i] or '.2021,' in file[i] or '.2022,' in file[i] or '.2023,' in \
                    file[
                        i] or '.2024,' in file[i]:
                if i == 0:
                    file[i] = file[i][18:-18]
                elif i == len(file) - 1:
                    pass
                else:
                    file[i] = file[i][:-18]
            elif i == len(file) - 1:
                pass
            else:
                file[i + 1] = file[i] + file[i + 1]
        dict = {}  # значения - массив со значениями: [Всего сообщений, количество символов, количество пробелов, количество пожеланий спокойной ночи, количество пожеланий доброго утра, количество медиа]
        for i in range(len(file)):
            if 'Сообщения и звонки защищены сквозным шифрованием. Третьи лица, включая WhatsApp' not in file[
                i] and 'Ваш код безопасности с пользователем' not in file[i]:
                # time.sleep(0.2)
                # print(file[i])
                name = file[i].split(': ')[0]
                mes = ': '.join(file[i].split(': ')[1:])
                if mes == '' or name == '':
                    continue
                lenght = len(mes)
                spaces = mes.count(' ')
                for j in sleep:
                    if j in mes:
                        sl = 1
                        break
                else:
                    sl = 0
                for j in morn:
                    if j in mes:
                        m = 1
                        break
                else:
                    m = 0
                med = mes.count('<Без медиафайлов>')
                if name in dict:
                    dict[name][0] += 1
                    dict[name][1] += lenght
                    dict[name][2] += spaces
                    dict[name][3] += sl
                    dict[name][4] += m
                    dict[name][5] += med

                else:
                    dict[name] = [0, 0, 0, 0, 0, 0]
                    dict[name][0] += 1
                    dict[name][1] += lenght
                    dict[name][2] += spaces
                    dict[name][3] += sl
                    dict[name][4] += m
                    dict[name][5] += med
        self.open_result(dict)


class Ui_Dialog(object):
    def setupUi(self, Dialog, dict):
        Dialog.setObjectName("Dialog")
        Dialog.resize(307, 579)
        self.indexes = dict.keys()
        self.values = list(dict.values())
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-50, 540, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 150, 121, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(60, 80, 191, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(self.indexes)

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 250, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 300, 161, 61))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 390, 171, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 470, 191, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(240, 150, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(240, 200, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(240, 250, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(240, 310, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(240, 410, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(240, 470, 47, 13))
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.comboBox.activated.connect(self.currentIndexChanged)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog",
                                      "<html><head/><body><p><span style=\" font-size:11pt;\">Всего сообщений</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:11pt;\">Количество символов</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:11pt;\">Количество пробелов</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:11pt;\">Количество пожеланий</span></p><p><span style=\" font-size:11pt;\"> спокойной ночи</span></p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:11pt;\">Количество пожеланий</span></p><p><span style=\" font-size:11pt;\">доброго утра</span></p><p><br/></p><p><br/></p></body></html>"))
        self.label_6.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:11pt;\">Количество медиафайлов</span></p></body></html>"))
        self.currentIndexChanged()

    def currentIndexChanged(self):
        index = self.comboBox.currentIndex()
        values = self.values[index]

        _translate = QtCore.QCoreApplication.translate
        self.label_7.setText(_translate("Dialog", str(values[0])))
        self.label_8.setText(_translate("Dialog", str(values[1])))
        self.label_9.setText(_translate("Dialog", str(values[2])))
        self.label_10.setText(_translate("Dialog", str(values[3])))
        self.label_11.setText(_translate("Dialog", str(values[4])))
        self.label_12.setText(_translate("Dialog", str(values[5])))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
